ScrollReveal().reveal("#nombre", {delay:500})
ScrollReveal().reveal("#juani", { delay: 800 })
ScrollReveal().reveal(".cartel", { delay: 500 })
ScrollReveal().reveal(".logico-matematica",{ delay: 500 })
ScrollReveal().reveal(".intrapersonal",{ delay: 1000 })
ScrollReveal().reveal(".creativa", { delay: 1500 })
ScrollReveal().reveal("#jardin", {delay:500})
ScrollReveal().reveal("#sala-5", {delay:500})
ScrollReveal().reveal("#primer-grado", {delay:500})
ScrollReveal().reveal("#grado-5", {delay:500})
ScrollReveal().reveal("#grado-6", {delay:500})
ScrollReveal().reveal("#comienzos", {delay:500})
ScrollReveal().reveal("#interes", {delay:500})
ScrollReveal().reveal("#actualidad", {delay:500})